-- LA TOLERANCIA QUE UN TURNO SOBRESCRIBE (23 de septiembre de 2026).
--
-- Pedido del dueño. Hasta hoy la tolerancia era SIEMPRE de la persona: la fijaba su horario y
-- pintarle un turno no se la tocaba. El caso que lo movió es real: un turno nocturno puede merecer
-- otra tolerancia que uno diurno, y eso es forma del turno, no política de la empresa.
--
-- NO se mudó la política al turno. Sigue viviendo en `horarios`; estas tres columnas solo dejan
-- que un turno la pise cuando haga falta.
--
-- POR QUÉ SON ANULABLES Y SIN `DEFAULT`, que es lo único delicado de este archivo:
--
--   NULL  = «la del horario». Es lo que tendrán las plantillas que ya existen, así que nada cambia
--           para nadie al aplicar esto.
--   0     = «sin tolerancia», la tardanza cuenta desde el primer minuto.
--
-- Son cosas distintas. Un `DEFAULT 0` borraría esa diferencia y convertiría, en silencio y de
-- golpe, TODAS las plantillas existentes en turnos sin tolerancia. El código que las lee usa `??`
-- y no `||` por esta misma razón, y hay pruebas que lo sujetan.
--
-- SALIÓ DE `prisma migrate diff`, no se escribió a mano. Y se le quitó una línea que el diff
-- proponía y que NO es de este cambio:
--
--   ALTER TABLE `colaboradores` ADD COLUMN `numeroContrato` VARCHAR(191) NULL;
--
-- Esa es del trabajo de la plantilla de Siigo (commit 2db2230), que tocó el mismo `schema.prisma`
-- en paralelo. Va en su propio archivo y la aplica quien la hizo: un SQL de despliegue no puede
-- arrastrar a producción un cambio de esquema que nadie decidió meter en este lote.
--
-- Es aditivo y sobre una tabla chica (el catálogo de turnos de una empresa), así que no necesita
-- ALGORITHM/LOCK explícitos como los ALTER de `registros`.
--
-- ============================================================================
-- ANTES DE CORRER NADA
-- ============================================================================
-- 1. Copia de seguridad de la base desde cPanel (Backup → Download a MySQL Database Backup).
-- 2. Entra a la base `ewyfwxbg_horapro` en phpMyAdmin ANTES de enviar. Aun así el nombre va
--    escrito abajo, que es la guarda de verdad (#1109 del 13 de septiembre de 2026).
-- 3. ESTE ARCHIVO VA DESPUÉS DE `sql/plantillas-turno.sql`, que es quien CREA `plantillas_turno`
--    (el único CREATE de esa tabla en todo el repositorio). No es un «si acaso»: pegado antes,
--    muere con el error 1146 (Table 'plantillas_turno' doesn't exist) sin tocar una sola columna.
--
--    Y el error de invertir el orden es SILENCIOSO en la otra dirección: `plantillas-turno.sql`
--    es idempotente por `CREATE TABLE IF NOT EXISTS`, así que corrido después no falla, no hace
--    nada, y su propia comprobación («tiene que devolver 15 columnas») devolvería 18 y se leería
--    como un fallo donde todo está bien.
--
--    El orden se comprueba, no se recuerda (CLAUDE.md §12.3). Corre esto PRIMERO:
--
--      SELECT COUNT(*) AS existe_plantillas_turno
--        FROM information_schema.TABLES
--       WHERE TABLE_SCHEMA = 'ewyfwxbg_horapro' AND TABLE_NAME = 'plantillas_turno';
--
--    0 = PARA y corre antes `sql/plantillas-turno.sql`.   1 = sigue.
-- 4. Este SQL va ANTES del backend nuevo, y el esquema cambió, así que el despliegue lleva CUATRO
--    ramas y no tres, con `prisma-build` por delante del backend (CLAUDE.md §11).

ALTER TABLE `ewyfwxbg_horapro`.`plantillas_turno`
  ADD COLUMN `toleranciaMin` INTEGER NULL,
  ADD COLUMN `toleranciaSalidaMin` INTEGER NULL,
  ADD COLUMN `ajustaEntrada` BOOLEAN NULL;

-- ============================================================================
-- COMPROBACIÓN
-- ============================================================================
-- Tres filas, las tres con IS_NULLABLE = YES y COLUMN_DEFAULT nulo. Un default aquí borraría la
-- diferencia entre «la del horario» y «sin tolerancia», que es lo único delicado de este archivo:
-- SELECT COLUMN_NAME, COLUMN_TYPE, IS_NULLABLE, COLUMN_DEFAULT
--   FROM information_schema.COLUMNS
--  WHERE TABLE_SCHEMA = 'ewyfwxbg_horapro' AND TABLE_NAME = 'plantillas_turno'
--    AND COLUMN_NAME IN ('toleranciaMin','toleranciaSalidaMin','ajustaEntrada');
--
-- Y todas las plantillas existentes tienen que quedar en NULL:
-- SELECT COUNT(*) AS con_tolerancia_propia FROM `ewyfwxbg_horapro`.`plantillas_turno`
--  WHERE `toleranciaMin` IS NOT NULL OR `toleranciaSalidaMin` IS NOT NULL
--     OR `ajustaEntrada` IS NOT NULL;   -- tiene que dar 0

-- ============================================================================
-- PARA REVERTIR
-- ============================================================================
-- ALTER TABLE `ewyfwxbg_horapro`.`plantillas_turno`
--   DROP COLUMN `toleranciaMin`, DROP COLUMN `toleranciaSalidaMin`, DROP COLUMN `ajustaEntrada`;
